import { query } from '../db/database';
import logger from '../config/logger';
import { TaskService } from './task.service';
import { ApprovalService } from './approval.service';
import { NotificationService } from './notification.service';
import { AuditService } from './audit.service';

export class WorkflowEngineService {
  /**
   * Handle an event triggered by the system
   */
  static async handleEvent(triggerType: 'email_received' | 'task_created' | 'approval_submitted', payload: any): Promise<void> {
    try {
      // Find active workflows matching this trigger type
      const { rows: workflows } = await query<any>(
        `SELECT * FROM workflows WHERE trigger_type = $1 AND status = 'active'`,
        [triggerType]
      );

      if (workflows.length === 0) {
        logger.debug(`No active workflows found for trigger: ${triggerType}`);
        return;
      }

      for (const workflow of workflows) {
        // Create pending execution record
        const { rows: execRows } = await query<any>(
          `INSERT INTO workflow_executions (workflow_id, trigger_payload, status)
           VALUES ($1, $2, 'pending')
           RETURNING id`,
          [workflow.id, payload]
        );
        const executionId = execRows[0].id;

        try {
          let logMessage = '';

          // Execute action based on action_type
          switch (workflow.action_type) {
            case 'create_task':
              await this.executeCreateTaskAction(payload);
              logMessage = 'Task successfully created via workflow.';
              break;
            case 'start_approval':
              await this.executeStartApprovalAction(payload);
              logMessage = 'Approval workflow successfully started via workflow.';
              break;
            case 'send_notification':
              // Send notification
              await NotificationService.createNotification({
                user_id: payload.userId, // Default to trigger user or admin
                title: payload.title || `Workflow Notification: ${workflow.name}`,
                message: payload.message || `The workflow "${workflow.name}" triggered a notification.`,
                type: 'info'
              });
              logger.info(`Workflow ${workflow.name} triggered send_notification.`);
              logMessage = 'Notification sent successfully.';
              break;
            default:
              throw new Error(`Unsupported action type: ${workflow.action_type}`);
          }

          // Mark success
          await query(
            `UPDATE workflow_executions SET status = 'success', logs = $1 WHERE id = $2`,
            [logMessage, executionId]
          );

          // Log workflow execution audit event
          await AuditService.log(
            payload.userId || null,
            'workflow_execution',
            'workflow',
            workflow.id,
            { executionId, status: 'success', logs: logMessage }
          );
        } catch (actionError) {
          logger.error(`Workflow ${workflow.id} execution failed:`, actionError);
          // Mark failed
          await query(
            `UPDATE workflow_executions SET status = 'failed', logs = $1 WHERE id = $2`,
            [(actionError as Error).message || String(actionError), executionId]
          );

          // Log workflow execution failure audit event
          await AuditService.log(
            payload.userId || null,
            'workflow_execution',
            'workflow',
            workflow.id,
            { executionId, status: 'failed', error: (actionError as Error).message }
          );
        }
      }
    } catch (error) {
      logger.error('Error in WorkflowEngineService.handleEvent:', error);
    }
  }

  private static async executeCreateTaskAction(payload: any) {
    // If an email was received, payload might contain subject, body.
    const title = payload.subject || payload.title || 'Automated Task from Workflow';
    const description = payload.body || payload.description || 'Auto-generated by system workflow.';
    const createdBy = payload.userId || 'admin@owh.com'; // Fallback to a system user or admin, ideally pass a real user.

    // Let's query an admin to act as created_by if missing
    let creatorId = payload.userId;
    if (!creatorId) {
      const { rows } = await query<any>(`SELECT id FROM users WHERE role = 'admin' LIMIT 1`);
      creatorId = rows[0]?.id;
    }

    if (!creatorId) throw new Error('No user found to assign as creator of automated task.');

    await TaskService.createTask({
      title,
      description,
      priority: 'medium',
    }, creatorId);
  }

  private static async executeStartApprovalAction(payload: any) {
    const title = payload.title ? `Approval required for: ${payload.title}` : 'Automated Approval Request';
    const description = payload.description || 'Auto-generated approval request via workflow.';
    
    // We need a requester and an approver.
    let requesterId = payload.userId;
    if (!requesterId) {
      const { rows } = await query<any>(`SELECT id FROM users LIMIT 1`);
      requesterId = rows[0]?.id;
    }

    // Default to a manager or admin
    const { rows: approverRows } = await query<any>(`SELECT id FROM users WHERE role IN ('admin', 'manager') AND id != $1 LIMIT 1`, [requesterId]);
    let approverId = approverRows[0]?.id;

    if (!approverId) {
      // Fallback if no manager found
      const { rows: anyUser } = await query<any>(`SELECT id FROM users WHERE id != $1 LIMIT 1`, [requesterId]);
      approverId = anyUser[0]?.id || requesterId; 
    }

    if (!requesterId || !approverId) throw new Error('Missing users to map requester and approver.');

    await ApprovalService.createApproval({
      title,
      description,
      approver_id: approverId,
      type: 'workflow_auto',
    }, requesterId);
  }
}
